os: linux
dist: xenial
language: php
php:
- 7.2
cache:
  directories:
  - "$HOME/.composer/cache/files"
jobs:
  include:
  - stage: deploy
    install: true
    before_install:
    - sudo apt-get update
    - sudo apt-get install graphviz
    script:
    - wget http://phpdox.de/releases/phpdox.phar && chmod +x phpdox.phar && sudo mv
      phpdox.phar /usr/local/bin/phpdox
    - mkdir build/ && php vendor/bin/phploc src --log-xml build/phploc.xml
    - phpdox
    after_success: true
    deploy:
      provider: pages
      skip_cleanup: true
      token: "$GITHUB_TOKEN"
      local_dir: build/docs/html
      on:
        branch: master
  - script:
    - yarn install
    - yarn semantic-release
    after_success: skip
    before_script: skip
    language: node_js
    node_js: 10
    php: skip
before_script:
- travis_retry composer install --prefer-dist
script:
- "./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml"
after_success:
- php vendor/bin/php-coveralls -v
